# For more details on the format and content:
# https://github.com/robocorp/rcc/blob/master/docs/recipes.md#what-is-in-condayaml

channels:
  - conda-forge

dependencies:
  # Define conda-forge packages here -> https://anaconda.org/search
  # When available, prefer the conda-forge version of a packages over pip.
  # Installations will be faster and more efficient.
  - python=3.9.13
  - pip=22.1.2
  - pip:
      # Define pip packages here -> https://pypi.org/
      - rpaframework==15.6.0 # https://rpaframework.org/releasenotes.html
